version: "3.5"

x-logging: 
      &default-logging
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  default:
    name: zkevm
services:
  zkevm-sequencer:
    container_name: zkevm-sequencer
    image: zkevm-node
    # ports:
      # - 9092:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
      - ZKEVM_NODE_POOL_HOST=zkevm-state-db
    volumes:
      - ./test.keystore:/pk/keystore
      - ./config/test.node.config.toml:/app/config.toml
      - ./config/test.genesis.config.json:/app/genesis.json
    logging: *default-logging
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --genesis /app/genesis.json --cfg /app/config.toml --components sequencer"

  zkevm-json-rpc:
    container_name: zkevm-json-rpc
    image: zkevm-node
    ports:
      - 8123:8123
      # - 9091:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
      - ZKEVM_NODE_POOL_HOST=zkevm-state-db
      - ZKEVM_NODE_RPC_DB_HOST=zkevm-state-db
      - ZKEVM_NODE_RPC_BROADCASTURI=zkevm-broadcast:61090
    volumes:
      - ./test.keystore:/pk/keystore
      - ./config/test.node.config.toml:/app/config.toml
      - ./config/test.genesis.config.json:/app/genesis.json
    logging: *default-logging
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --genesis /app/genesis.json --cfg /app/config.toml --components rpc"

  zkevm-aggregator:
    container_name: zkevm-aggregator
    image: zkevm-node
    ports:
      - "127.0.0.1:50081:50081"
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
    volumes:
      - ./test.keystore:/pk/keystore
      - ./config/test.node.config.toml:/app/config.toml
      - ./config/test.genesis.config.json:/app/genesis.json
    logging: *default-logging
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --genesis /app/genesis.json --cfg /app/config.toml --components aggregator"

  zkevm-sync:
    container_name: zkevm-sync
    image: zkevm-node
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
    volumes:
      - ./test.keystore:/pk/keystore
      - ./config/test.node.config.toml:/app/config.toml
      - ./config/test.genesis.config.json:/app/genesis.json
    logging: *default-logging
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --genesis /app/genesis.json --cfg /app/config.toml --components synchronizer"

  zkevm-broadcast:
    container_name: zkevm-broadcast
    image: zkevm-node
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
    ports:
      - "127.0.0.1:61090:61090"
    volumes:
      - ./test.keystore:/pk/keystore
      - ./config/test.node.config.toml:/app/config.toml
      - ./config/test.genesis.config.json:/app/genesis.json
    logging: *default-logging
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --genesis /app/genesis.json --cfg /app/config.toml --components broadcast-trusted-state"

  zkevm-state-db:
    container_name: zkevm-state-db
    image: postgres
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./config/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    logging: *default-logging
    environment:
      - POSTGRES_USER=state_user
      - POSTGRES_PASSWORD=state_password
      - POSTGRES_DB=state_db
    command: ["postgres", "-N", "500"]

  zkevm-explorer-l2:
    container_name: zkevm-explorer-l2
    image: hermeznetwork/zkevm-explorer:latest
    ports:
      - 4000:4000
    environment:
      - NETWORK=POE
      - SUBNETWORK=Polygon Hermez
      - COIN=ETH
      - ETHEREUM_JSONRPC_VARIANT=geth
      - ETHEREUM_JSONRPC_HTTP_URL=http://zkevm-explorer-json-rpc:8124
      - DATABASE_URL=postgres://state_user:state_password@zkevm-state-db:5432/l2_explorer_db
      - ECTO_USE_SSL=false
      - MIX_ENV=prod
      - LOGO=/images/blockscout_logo.svg
      - LOGO_FOOTER=/images/blockscout_logo.svg
    logging: *default-logging
    command:
      ["/bin/sh", "-c", "mix do ecto.create, ecto.migrate; mix phx.server"]

  zkevm-explorer-json-rpc:
    container_name: zkevm-explorer-json-rpc
    image: zkevm-node
    ports:
      - 8124:8124
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
      - ZKEVM_NODE_POOL_HOST=zkevm-state-db
      - ZKEVM_NODE_RPC_DB_HOST=zkevm-state-db
      - ZKEVM_NODE_RPC_PORT=8124
    volumes:
      - ./test.keystore:/pk/keystore
      - ./config/test.node.config.toml:/app/config.toml
      - ./config/test.genesis.config.json:/app/genesis.json
    logging: *default-logging
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --genesis /app/genesis.json --cfg /app/config.toml --components rpc --http.api eth,net,debug,zkevm,txpool,web3"

  zkevm-prover:
    container_name: zkevm-prover
    image: hermeznetwork/zkevm-prover:5a4c49d
    ports:
      - "127.0.0.1:50051:50051" # Prover
      - "127.0.0.1:50052:50052" # Mock prover
      - "127.0.0.1:50061:50061" # MT
      - "127.0.0.1:50071:50071" # Executor
    volumes:
      - ./config/test.prover.config.json:/usr/src/app/config.json
    logging: *default-logging
    command: >
      zkProver -c /usr/src/app/config.json

  zkevm-bridge-service:
    container_name: zkevm-bridge-service
    image: zkevm-bridge-service
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - ZKEVM_BRIDGE_DATABASE_USER=state_user
      - ZKEVM_BRIDGE_DATABASE_PASSWORD=state_password
      - ZKEVM_BRIDGE_DATABASE_NAME=test_db
      - ZKEVM_BRIDGE_DATABASE_HOST=zkevm-state-db
      - ZKEVM_BRIDGE_DATABASE_PORT=5432
    volumes:
      - ./config/test.bridge.config.toml:/app/config.toml
    logging: *default-logging
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-bridge run --cfg /app/config.toml"

  zkevm-bridge-ui:
    container_name: zkevm-bridge-ui
    image: zkevm-bridge-ui:local
    ports:
      - 8090:80
    # volumes:
    #   - ./config/bridge-ui-deploy.sh:/app/scripts/deploy.sh
    #   - ./config/bridge-ui.env:/app/.env
    environment:
      - ETHEREUM_RPC_URL=https://exchaintestrpc.okex.org
      - ETHEREUM_EXPLORER_URL=https://www.oklink.com/zh-cn/okc-test/
      - ETHEREUM_BRIDGE_CONTRACT_ADDRESS=0x202CCe504e04bEd6fC0521238dDf04Bc9E8E15aB
      - ETHEREUM_PROOF_OF_EFFICIENCY_CONTRACT_ADDRESS=0xf4B146FbA71F41E0592668ffbF264F1D186b2Ca8
      - POLYGON_ZK_EVM_RPC_URL=https://zkevm.exchaindevrpc.com
      - POLYGON_ZK_EVM_EXPLORER_URL=http://zkevm-explorer.exchaindevrpc.com
      - POLYGON_ZK_EVM_BRIDGE_CONTRACT_ADDRESS=0x9d98deabc42dd696deb9e40b4f1cab7ddbf55988
      - POLYGON_ZK_EVM_NETWORK_ID=1
      - BRIDGE_API_URL=http://zkevm-bridge.exchaindevrpc.com
      - USE_FIAT_EXCHANGE_RATES=false
      - SHOW_OUTDATED_NETWORK_MODAL=false
    logging: *default-logging







