[Log]
Level = "debug"
Outputs = ["stdout"]

[SyncDB]
Database = "postgres"
User = "test_user"
Password = "test_password"
Name = "test_db"
Host = "zkevm-bridge-db"
Port = "5432"
MaxConns = 20

[ClaimTxManager]
Enabled = false 
FrequencyToMonitorTxs = "1s"
PrivateKey = {Path = "/pk/keystore.claimtxmanager", Password = "testonly"}
RetryInterval = "1s"
RetryNumber = 10

[Etherman]
L1URL = "https://goerli.infura.io/v3/bb410aa66f77424ab0260937600de8a5"
L2URLs = ["http://8.217.101.128:8123"]

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 100

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"
CacheSize = 100000
DefaultPageLimit = 25
MaxPageLimit = 100
BridgeVersion = "v1"
    [BridgeServer.DB]
    Database = "postgres"
    User = "test_user"
    Password = "test_password"
    Name = "test_db"
    Host = "zkevm-bridge-db"
    Port = "5432"
    MaxConns = 20

[NetworkConfig]
GenBlockNumber = 9466743 
PolygonBridgeAddress = "0xEA0873c537a7f814b9723178cC1b3d956b335682"
PolygonZkEVMGlobalExitRootAddress = "0x35170307708974016eF23Cc8311E161a7c199beb"
L2PolygonBridgeAddresses = ["0xEA0873c537a7f814b9723178cC1b3d956b335682"]
#L1ChainID = 5
