[Log]
Level = "debug"
Outputs = ["stdout"]

[SyncDB]
Database = "postgres"
User = "test_user"
Password = "test_password"
Name = "test_db"
Host = "zkevm-bridge-db"
Port = "5432"
MaxConns = 20

[ClaimTxManager]
Enabled = false 
FrequencyToMonitorTxs = "1s"
PrivateKey = {Path = "/pk/keystore.claimtxmanager", Password = "testonly"}

[Etherman]
L1URL = "https://goerli.infura.io/v3/0d081e04621c4c69b12649fbb63ef18a"
L2URLs = ["http://44.232.123.15:8123"]

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 100

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"
CacheSize = 100000
DefaultPageLimit = 25
MaxPageLimit = 100
BridgeVersion = "v1"
    [BridgeServer.DB]
    Database = "postgres"
    User = "test_user"
    Password = "test_password"
    Name = "test_db"
    Host = "zkevm-bridge-db"
    Port = "5432"
    MaxConns = 20

[NetworkConfig]
GenBlockNumber = 9477243 
PolygonZkEVMAddress = "0xA15e6546Aadc0449276231bD5f402d37666013B4"
PolygonBridgeAddress = "0xD253245F00Fc7e65A9CD804AC45DD484762e02fC"
PolygonZkEVMGlobalExitRootAddress = "0xaaFC8543f9e0F231d1E7d094028337090Ec6331E"
MaticTokenAddress = "0x40152A28d32383D62d6B133094Cf0a8211a81fBF"
L2PolygonBridgeAddresses = ["0xD253245F00Fc7e65A9CD804AC45DD484762e02fC"]
L1ChainID =  5
