[Log]
Level = "info"
Outputs = ["stdout"]

[Database]
Database = "postgres"
User = "test_user"
Password = "test_password"
Name = "test_db"
Host = "zkevm-bridge-db"
Port = "5435"
MaxConns = 20

[Etherman]
L1URL = "https://exchaintestrpc.okex.org"
L2URLs = ["http://zkevm-json-rpc:8123"]

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 200
GrpcURL = "zkevm-broadcast:61090"

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"

[NetworkConfig]
GenBlockNumber = 17853079
PoEAddr = "0xE42219e62CDa1ed6089Db541e79CE97931b1b6EB"
BridgeAddr = "0x53C873AEb867a6103780090Cbc0e06fEab13Af07"
GlobalExitRootManAddr = "0x2bfCD8AC69e7a48BcB809C428F5A7b673cA7D2fD"
MaticAddr = "0x738dee6Eb31748c2e8F779dc5a26A6F95F3616A5"
L2BridgeAddrs = ["0x9d98deabc42dd696deb9e40b4f1cab7ddbf55988"]
L1ChainID = 65
