[Log]
Level = "info"
Outputs = ["stdout"]

[Database]
Database = "postgres"
User = "test_user"
Password = "test_password"
Name = "test_db"
Host = "zkevm-bridge-db"
Port = "5435"
MaxConns = 20

[Etherman]
L1URL = "https://exchaintestrpc.okex.org"
L2URLs = ["http://zkevm-json-rpc:8123"]

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 200
GrpcURL = "zkevm-broadcast:61090"

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"

[NetworkConfig]
GenBlockNumber = 17762817
PoEAddr = "0x54735bd19E31B304F87051f5adc343D0501d79bE"
BridgeAddr = "0x9C177B8e52CeF403B419f4c8D04bf3091a3Bce6C"
GlobalExitRootManAddr = "0xC4538222686D60BFeC4d41Fb2acdd1667a99e3D9"
MaticAddr = "0x83e20C8912635EBfaed286b7D6f03a2537b422e3"
L2BridgeAddrs = ["0x9d98deabc42dd696deb9e40b4f1cab7ddbf55988"]
L1ChainID = 65
