[Log]
Level = "info"
Outputs = ["stdout"]

[Database]
Database = "postgres"
User = "test_user"
Password = "test_password"
Name = "test_db"
Host = "zkevm-bridge-db"
Port = "5435"
MaxConns = 20

[Etherman]
L1URL = "https://goerli.infura.io/v3/bb410aa66f77424ab0260937600de8a5"
L2URLs = ["http://zkevm-json-rpc:8123"]

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 200
GrpcURL = "zkevm-sequencer:61090"

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"

[NetworkConfig]
GenBlockNumber = 8343697
PoEAddr = "0x71Df81Ad9262e090eb6370B687067c965232A974"
BridgeAddr = "0xDE0F5CF5443a5373db452f53f3B21055840D7cbF"
GlobalExitRootManAddr = "0x5C3F31F1F19566811Ccc5839A6C32059CAFC6a20"
MaticAddr = "0xe5BB221835388890743B267245363C3878de90a1"
L2BridgeAddrs = ["0x9d98deabc42dd696deb9e40b4f1cab7ddbf55988"]
L1ChainID = 5
