[Log]
Level = "info"
Outputs = ["stdout"]

[Database]
Database = "postgres"
User = "test_user"
Password = "test_password"
Name = "test_db"
Host = "zkevm-bridge-db"
Port = "5435"
MaxConns = 20

[Etherman]
L1URL = "https://exchaintestrpc.okex.org"
L2URLs = ["http://zkevm-json-rpc:8123"]

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 200
GrpcURL = "zkevm-broadcast:61090"

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"

[NetworkConfig]
GenBlockNumber = 17529100
PoEAddr = "0xc0F115A19107322cFBf1cDBC7ea011C19EbDB4F8"
BridgeAddr = "0xF8e31cb472bc70500f08Cd84917E5A1912Ec8397"
GlobalExitRootManAddr = "0xD5ac451B0c50B9476107823Af206eD814a2e2580"
MaticAddr = "0x4b6aB5F819A515382B0dEB6935D793817bB4af28"
L2BridgeAddrs = ["0x9d98deabc42dd696deb9e40b4f1cab7ddbf55988"]
L1ChainID = 65