[Log]
Level = "info"
Outputs = ["stdout"]

[Database]
Database = "postgres"
User = "test_user"
Password = "test_password"
Name = "test_db"
Host = "zkevm-bridge-db"
Port = "5435"
MaxConns = 20

[Etherman]
L1URL = "https://exchaintestrpc.okex.org"
L2URLs = ["http://zkevm-json-rpc:8123"]

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 200
GrpcURL = "zkevm-broadcast:61090"

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"

[NetworkConfig]
GenBlockNumber = 17531500
PoEAddr = "0x3aAde2dCD2Df6a8cAc689EE797591b2913658659"
BridgeAddr = "0xffa7CA1AEEEbBc30C874d32C7e22F052BbEa0429"
GlobalExitRootManAddr = "0x5bf5b11053e734690269C6B9D438F8C9d48F528A"
MaticAddr = "0x3347B4d90ebe72BeFb30444C9966B2B990aE9FcB"
L2BridgeAddrs = ["0x9d98deabc42dd696deb9e40b4f1cab7ddbf55988"]
L1ChainID = 65