[Log]
Level = "info"
Outputs = ["stdout"]

[Database]
Database = "postgres"
User = "test_user"
Password = "test_password"
Name = "test_db"
Host = "zkevm-bridge-db"
Port = "5435"
MaxConns = 20

[Etherman]
L1URL = "https://goerli.infura.io/v3/bb410aa66f77424ab0260937600de8a5"
L2URLs = ["http://zkevm-json-rpc:8123"]

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 200
GrpcURL = "zkevm-sequencer:61090"

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"

[NetworkConfig]
GenBlockNumber = 8325519
PoEAddr = "0x4b4dbb855DD2f3CcA9B9e1bB73C487865b8ab0D2"
BridgeAddr = "0x6415fd18D936DbfAe0a1cC3e24A0cBCAD12dD24e"
GlobalExitRootManAddr = "0x055Cfd083610e1e747172AcD3B2e8c06Bf4c1220"
MaticAddr = "0x4B53839f1FE653fF86c077F9c618191803A3e9A9"
L2BridgeAddrs = ["0x9d98deabc42dd696deb9e40b4f1cab7ddbf55988"]
L1ChainID = 5
