[Log]
Level = "info"
Outputs = ["stdout"]

[Database]
Database = "postgres"
User = "test_user"
Password = "test_password"
Name = "test_db"
Host = "zkevm-bridge-db"
Port = "5435"
MaxConns = 20

[Etherman]
L1URL = "https://exchaintestrpc.okex.org"
L2URLs = ["http://zkevm-json-rpc:8123"]

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 200
GrpcURL = "zkevm-broadcast:61090"

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"

[NetworkConfig]
GenBlockNumber = 17758100
PoEAddr = "0x99dBE4AEa58E518C50a1c04aE9b48C9F6354612f"
BridgeAddr = "0xF32D39ff9f6Aa7a7A64d7a4F00a54826Ef791a55"
GlobalExitRootManAddr = "0x8A93d247134d91e0de6f96547cB0204e5BE8e5D8"
MaticAddr = "0x5fc748f1FEb28d7b76fa1c6B07D8ba2d5535177c"
L2BridgeAddrs = ["0x9d98deabc42dd696deb9e40b4f1cab7ddbf55988"]
L1ChainID = 65
