[Log]
Level = "info"
Outputs = ["stdout"]

[Database]
Database = "postgres"
User = "test_user"
Password = "test_password"
Name = "test_db"
Host = "zkevm-bridge-db"
Port = "5435"
MaxConns = 20

[Etherman]
L1URL = "https://exchaintestrpc.okex.org"
L2URLs = ["http://zkevm-json-rpc:8123"]

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 200
GrpcURL = "zkevm-broadcast:61090"

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"

[NetworkConfig]
GenBlockNumber = 17855403
PoEAddr = "0x9dCD4A1dDFe3B38e6156563F91A6096C0298Aa97"
BridgeAddr = "0x5f5f62E93E2a5a876ad763daf39371d665Da4A6E"
GlobalExitRootManAddr = "0x26123a5036D3ee8300743226815df5F7D02b4621"
MaticAddr = "0x3143747f3d104e05B3612A0A946a519c98c83e1D"
L2BridgeAddrs = ["0x9d98deabc42dd696deb9e40b4f1cab7ddbf55988"]
L1ChainID = 65
