[Log]
Level = "info"
Outputs = ["stdout"]

[Database]
Database = "postgres"
User = "test_user"
Password = "test_password"
Name = "test_db"
Host = "zkevm-bridge-db"
Port = "5435"
MaxConns = 20

[Etherman]
L1URL = "https://exchaintestrpc.okex.org"
L2URLs = ["http://zkevm-json-rpc:8123"]

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 200
GrpcURL = "zkevm-broadcast:61090"

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"

[NetworkConfig]
GenBlockNumber = 17800755
PoEAddr = "0x7a28bC47A32374E49090E331ee4a04705B8C901A"
BridgeAddr = "0x2B00322Efe2d0a23F1c47af675A0E9F98796390c"
GlobalExitRootManAddr = "0xE7153Adf09F6EccedfFAA935F1d6E57D86996793"
MaticAddr = "0x6f6665e4Ab3B51B014B63a13089169BB81f053e1"
L2BridgeAddrs = ["0x9d98deabc42dd696deb9e40b4f1cab7ddbf55988"]
L1ChainID = 65
